/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.GameController;

/**
 *
 * @author CtSec
 */
public class FrmDificuldade extends javax.swing.JFrame {

    /**
     * Creates new form FrmIniciar
     */
    public FrmDificuldade() {
        initComponents();
        this.setTitle("SustentableQuiz");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDificil = new javax.swing.JButton();
        btnFacil = new javax.swing.JButton();
        btnMedio = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(904, 553));
        getContentPane().setLayout(null);

        btnDificil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Dificil.jpeg"))); // NOI18N
        btnDificil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDificilActionPerformed(evt);
            }
        });
        getContentPane().add(btnDificil);
        btnDificil.setBounds(590, 360, 200, 100);

        btnFacil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Facil.jpeg"))); // NOI18N
        btnFacil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacilActionPerformed(evt);
            }
        });
        getContentPane().add(btnFacil);
        btnFacil.setBounds(130, 360, 200, 100);

        btnMedio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Medio.jpeg"))); // NOI18N
        btnMedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMedioActionPerformed(evt);
            }
        });
        getContentPane().add(btnMedio);
        btnMedio.setBounds(360, 360, 200, 100);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/FundoDificuldade.jpeg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 910, 550);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    GameController GC = new GameController();
    
    private void btnFacilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacilActionPerformed
       FrmQuestion1 FQ = new FrmQuestion1();
       FrmQuestion5 Fq5 = new FrmQuestion5();
       Fq5.Dificuldade = GC.SelectLevel(1);
       FQ.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnFacilActionPerformed

    private void btnDificilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDificilActionPerformed
       FrmQuestion1 FQ = new FrmQuestion1();
       GC.SelectLevel(3);
       FQ.setVisible(true);
       this.dispose();
    }//GEN-LAST:event_btnDificilActionPerformed

    private void btnMedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMedioActionPerformed
        FrmQuestion1 FQ = new FrmQuestion1();
        FrmQuestion_10 Fq5 = new FrmQuestion_10();
        Fq5.Dificuldade = GC.SelectLevel(2);
        FQ.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMedioActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDificuldade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDificuldade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDificuldade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDificuldade.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmDificuldade().setVisible(true);
            }
        });
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDificil;
    private javax.swing.JButton btnFacil;
    private javax.swing.JButton btnMedio;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
